a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

print("Addition :", a + b)
print("Subtraction :", a - b)
print("Multiplication :", a * b)
print("Division :", a / b)
print("Integer division :", a // b)
print("Remainder :", a % b)
print("Exponentiation :", a ** b)
